### ISSUE TITLE
 a.forEach is not a function

### ISSUE THREAD

**Issue by reggi** [xxorax/node-shell-escape#7]
/Users/thomas/Desktop/figaro/node_modules/shell-escape/shell-escape.js:7
  a.forEach(function(s) {
    ^
TypeError: a.forEach is not a function
    at shellescape (/Users/thomas/Desktop/figaro/node_modules/shell-escape/shell-escape.js:7:5)
    at Object.<anonymous> (/Users/thomas/Desktop/figaro/search-deps/index.js:16:14)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:472:10)
    at startup (node.js:124:18)
    at node.js:959:3

**Comment by reggi** [comment]
Whoops didn't know it took an array :(

**Comment by Ajay-MS** [comment]
TypeError: a.forEach is not a function
    at shellescape (E:\GithubNew\<user>\node_modules\shell-escape\shell-escape.js:7:5)
